
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-08T11:19:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "48f3c8c463d37fe08f2e129260868b07080f9b9e",
 "version": "0.0.3+10.g48f3c8c"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
